# Generated by Django 2.0 on 2019-12-06 13:18

import chordnote_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=500, null=True)),
                ('profile_photo', models.ImageField(null=True, upload_to=chordnote_app.models.get_profile_photo_path)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chordnote_app.Book')),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Checkcode',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'checkcode',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('like_num', models.IntegerField(default=0)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(null=True)),
                ('image', models.ImageField(upload_to=chordnote_app.models.get_image_path)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('like_num', models.IntegerField(default=0)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('music_file', models.FileField(null=True, upload_to=chordnote_app.models.get_musci_file_path)),
            ],
            options={
                'db_table': 'moment',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('is_right', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'option',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('content_file', models.FileField(null=True, upload_to=chordnote_app.models.get_content_file_path)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chordnote_app.Chapter')),
            ],
            options={
                'db_table': 'period',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=500)),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chordnote_app.Period')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=32, null=True)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.IntegerField(null=True)),
                ('birth_date', models.CharField(max_length=16, null=True)),
                ('description', models.CharField(max_length=64, null=True)),
                ('image', models.ImageField(null=True, upload_to=chordnote_app.models.get_user_image_path)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='User_collect_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chordnote_app.Comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chordnote_app.User')),
            ],
            options={
                'db_table': 'user_collect_comment',
            },
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chordnote_app.Question'),
        ),
        migrations.AddField(
            model_name='moment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chordnote_app.User'),
        ),
        migrations.AddField(
            model_name='image',
            name='moment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chordnote_app.Moment'),
        ),
        migrations.AddField(
            model_name='image',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chordnote_app.Question'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chordnote_app.User'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('name', 'book')},
        ),
    ]
