# Generated by Django 2.0 on 2019-12-08 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chordnote_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_collect_Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chordnote_app.Moment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chordnote_app.User')),
            ],
            options={
                'db_table': 'user_collect_moment',
            },
        ),
    ]
